User.create!([
  {email: "testadmqin1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testadm32qin1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testadm312qin1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasdm312qin1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testassdm312qin1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddm312qin1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddm312qiqn1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddmqw312qiqn1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddmqw312qwsaqiqn1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddmqw312qwdssaqiqn1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddmqdsxcw312qwdssaqiqn1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddmqdsxcw312qwdssaqxzciqn1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddmqdzxsxcw312qwdssaqxzciqn1@mvmanor.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "testasssddmqdzxsxcw312qwdssaqxzciqn1@mv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "sxasx@mv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "sxasxq@mv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "sxasxqw@mv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "sxasxqw@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "sxasxqsxw@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "sxasx1qsxw@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "qwerrty@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "qwerrtyq@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "qwerr123edsrtadfvsxyq@asxmv.co.uksdc", password: "testadminuser", name: "Helppp"},
  {email: "qwerrtasxyq@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "qwerr123tasxyq@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "qwerr123ertasxyq@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "qwerr123ertadfvsxyq@asxmv.co.uk", password: "testadminuser", name: "Helppp"},
  {email: "qwerr123ertadfvsxyq@asxmv.co.uksdc", password: "testadminuser", name: "Helppp"},

])
